// <auto-generated />
using Data.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "portfolio-1.jpg",
                            IsDeleted = false,
                            Name = "Stationary",
                            Summary = "A yellow pencil with envelopes on a clean, blue backdrop!"
                        },
                        new
                        {
                            Id = 2,
                            Image = "portfolio-1.jpg",
                            IsDeleted = false,
                            Name = "Stationary",
                            Summary = "A yellow pencil with envelopes on a clean, blue backdrop!"
                        },
                        new
                        {
                            Id = 3,
                            Image = "portfolio-1.jpg",
                            IsDeleted = false,
                            Name = "Stationary",
                            Summary = "A yellow pencil with envelopes on a clean, blue backdrop!"
                        },
                        new
                        {
                            Id = 4,
                            Image = "portfolio-1.jpg",
                            IsDeleted = false,
                            Name = "Stationary",
                            Summary = "A yellow pencil with envelopes on a clean, blue backdrop!"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
